"""
SQLAlchemy 2.0 schema for the meeting store.

Design notes
------------
Everything the JSON store kept as a nested list is a real table with a real
foreign key. `transcript`, `speakerStats`, `languages`, `decisions`,
`actionItems` and `keywords` were all arrays inside one blob; each is now
ordered, indexed and independently queryable.

`decisions`, `action_items` and `keywords` are filled in by the summarization
stage (`models/summarizer.py`) once a meeting finishes transcribing. A meeting
that has not been summarized yet (still processing, or the summarizer produced
nothing usable) simply has empty collections here — the API contract already
returns those keys as empty lists in that case.

`decisions.quote` / `action_items.quote` are the verbatim transcript line each
item was verified against (see `summarizer.verify_quote`); `source_time` is
that line's display timestamp. Both are nullable because the extractive
fallback engine sets quote equal to the item's own text (it never proposes
anything the transcript didn't literally say), while older rows written before
this column existed have neither. The UI uses them to show *why* an insight is
on screen, not just that it is.

Ordering is explicit via a `position` column rather than relying on insertion
order, because SQL makes no ordering guarantee without ORDER BY. Speaker colours
depend on first-appearance order, so this matters.

Cascades are declared both in the database (`ondelete="CASCADE"`) and in the ORM
(`cascade="all, delete-orphan"`). The database constraint is the one that
actually guarantees no orphans; the ORM setting keeps in-session state correct.
"""

from __future__ import annotations

import datetime as dt

from sqlalchemy import (
    CheckConstraint,
    DateTime,
    Float,
    ForeignKey,
    Index,
    Integer,
    String,
    Text,
    UniqueConstraint,
    func,
)
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column, relationship


class Base(DeclarativeBase):
    pass


# Meeting.status is constrained rather than free text — the frontend switches
# on these three exact values, so a typo server-side would silently break the
# UI's polling and status pills.
MEETING_STATUSES = ("Processing", "Completed", "Failed")


class Meeting(Base):
    __tablename__ = "meetings"

    # Human-readable ids (MTG-<hex>) generated by the API, not surrogate ints.
    # They appear in URLs and in the audio directory name on disk.
    id: Mapped[str] = mapped_column(String(64), primary_key=True)

    title: Mapped[str] = mapped_column(String(512), nullable=False)
    agenda: Mapped[str | None] = mapped_column(Text)

    file_name: Mapped[str] = mapped_column(String(512), nullable=False)
    file_type: Mapped[str | None] = mapped_column(String(255))
    file_size_bytes: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    file_size_label: Mapped[str | None] = mapped_column(String(32))

    uploaded_at: Mapped[dt.datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now(), index=True
    )

    status: Mapped[str] = mapped_column(String(16), nullable=False, default="Processing", index=True)
    progress: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    error: Mapped[str | None] = mapped_column(Text)
    audio_quality_warning: Mapped[str | None] = mapped_column(Text)
    failed_segments: Mapped[int] = mapped_column(Integer, nullable=False, default=0)

    duration: Mapped[str | None] = mapped_column(String(32))
    duration_seconds: Mapped[float] = mapped_column(Float, nullable=False, default=0.0)
    participants: Mapped[int] = mapped_column(Integer, nullable=False, default=0)

    # Dominant language name, denormalised from meeting_languages for the list
    # view. Recomputed whenever languages are replaced.
    language: Mapped[str | None] = mapped_column(String(64))

    summary: Mapped[str | None] = mapped_column(Text)

    # Which engine wrote `summary` — a model name, or "extractive". Recorded
    # because prose is the one output that cannot be citation-checked: decisions
    # and action items are dropped unless their quote is found in the
    # transcript, but a paraphrase has no line to match against. The UI labels
    # the summary with this rather than presenting generated text as extracted.
    summary_engine: Mapped[str | None] = mapped_column(String(64))

    created_at: Mapped[dt.datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )
    updated_at: Mapped[dt.datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now(), onupdate=func.now()
    )
    deleted_at: Mapped[dt.datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True, index=True
    )

    # Per-meeting STT selection (see backend/stt/). NULL means "not set" and
    # is resolved to config.DEFAULT_PROCESSING_MODE ("local") by
    # stt/resolver.py — nullable rather than a hard default so existing rows
    # created before this column existed keep working with zero migration
    # data-fixup and unambiguously mean "local, as before".
    processing_mode: Mapped[str | None] = mapped_column(String(16), nullable=True)
    # Only meaningful when processing_mode="cloud". NULL falls back to
    # config.CLOUD_STT_DEFAULT_PROVIDER ("sarvam" today).
    stt_provider: Mapped[str | None] = mapped_column(String(32), nullable=True)

    transcript_lines: Mapped[list[TranscriptLine]] = relationship(
        back_populates="meeting",
        cascade="all, delete-orphan",
        order_by="TranscriptLine.position",
        lazy="selectin",
    )
    speaker_stats: Mapped[list[SpeakerStat]] = relationship(
        back_populates="meeting",
        cascade="all, delete-orphan",
        order_by="SpeakerStat.position",
        lazy="selectin",
    )
    languages: Mapped[list[MeetingLanguage]] = relationship(
        back_populates="meeting",
        cascade="all, delete-orphan",
        order_by="MeetingLanguage.position",
        lazy="selectin",
    )
    decisions: Mapped[list[Decision]] = relationship(
        back_populates="meeting",
        cascade="all, delete-orphan",
        order_by="Decision.position",
        lazy="selectin",
    )
    action_items: Mapped[list[ActionItem]] = relationship(
        back_populates="meeting",
        cascade="all, delete-orphan",
        order_by="ActionItem.position",
        lazy="selectin",
    )
    keywords: Mapped[list[Keyword]] = relationship(
        back_populates="meeting",
        cascade="all, delete-orphan",
        order_by="Keyword.position",
        lazy="selectin",
    )

    __table_args__ = (
        CheckConstraint(
            "status IN ('Processing', 'Completed', 'Failed')", name="ck_meetings_status"
        ),
        CheckConstraint("progress >= 0 AND progress <= 100", name="ck_meetings_progress"),
        CheckConstraint("file_size_bytes >= 0", name="ck_meetings_file_size"),
        # The list view is always "newest first".
        Index("ix_meetings_uploaded_at_desc", uploaded_at.desc()),
        CheckConstraint(
            "processing_mode IS NULL OR processing_mode IN ('local', 'cloud')",
            name="ck_meetings_processing_mode",
        ),
    )


class TranscriptLine(Base):
    """
    One diarized, single-speaker utterance.

    Language is per line, not per meeting — a trilingual meeting code-switches
    mid-conversation, and that fact is the product.
    """

    __tablename__ = "transcript_lines"

    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    meeting_id: Mapped[str] = mapped_column(
        ForeignKey("meetings.id", ondelete="CASCADE"), nullable=False, index=True
    )
    position: Mapped[int] = mapped_column(Integer, nullable=False)

    start_sec: Mapped[float] = mapped_column(Float, nullable=False, default=0.0)
    end_sec: Mapped[float] = mapped_column(Float, nullable=False, default=0.0)
    time_label: Mapped[str | None] = mapped_column(String(16))

    speaker: Mapped[str] = mapped_column(String(255), nullable=False, index=True)
    speaker_label: Mapped[str | None] = mapped_column(String(255))
    identified_as: Mapped[str | None] = mapped_column(String(255))
    confidence: Mapped[float] = mapped_column(Float, nullable=False, default=0.0)
    color: Mapped[str | None] = mapped_column(String(16))

    language: Mapped[str | None] = mapped_column(String(8), index=True)
    language_name: Mapped[str | None] = mapped_column(String(64))
    language_prob: Mapped[float] = mapped_column(Float, nullable=False, default=0.0)
    language_detected: Mapped[str | None] = mapped_column(String(8))
    # True when detection was near chance and the meeting's dominant language
    # was used instead. The UI flags these so a reader can distrust them.
    language_fallback: Mapped[bool] = mapped_column(nullable=False, default=False)
    # Every language spoken in this turn, comma-separated in first-heard order
    # ("en,mr"), set only when there is more than one. `language` above is the
    # dominant one; without this column a code-switched turn is indistinguishable
    # from a single-language one once it has been through the database, and the
    # UI's "mixed" badge could never fire on an uploaded meeting.
    # Comma-joined rather than JSON so SQLite (tests) and Postgres behave the same.
    language_mix: Mapped[str | None] = mapped_column(String(64))
    # Two languages scored almost equally on this segment — usually because
    # both were spoken in it, with no pause for the segmenter to cut on. The
    # line was still transcribed as a single language by a single engine, so
    # the minority half is probably wrong. Detection only; nothing splits a
    # segment on language yet.
    language_mixed_suspected: Mapped[bool] = mapped_column(nullable=False, default=False)
    # Gap between the top two candidate languages. Stored as well as the flag
    # so the threshold can be re-tuned against transcripts already on disk
    # instead of requiring a reprocess. 1.0 = detector was certain.
    language_margin: Mapped[float] = mapped_column(Float, nullable=False, default=1.0)

    # Raw ASR verbatim output; cleaned_text is the readable turn after merge/cleanup.
    raw_text: Mapped[str | None] = mapped_column(Text)
    cleaned_text: Mapped[str | None] = mapped_column(Text)
    # Display field — mirrors cleaned_text when present, else raw/text legacy.
    text: Mapped[str] = mapped_column(Text, nullable=False, default="")

    meeting: Mapped[Meeting] = relationship(back_populates="transcript_lines")

    __table_args__ = (
        UniqueConstraint("meeting_id", "position", name="uq_transcript_meeting_position"),
        CheckConstraint("end_sec >= start_sec", name="ck_transcript_time_order"),
        # Composite index for the common "all lines of one meeting, in order".
        Index("ix_transcript_meeting_position", "meeting_id", "position"),
    )


class SpeakerStat(Base):
    """Talk-time per speaker. `position` preserves first-appearance order,
    which is what assigns each speaker their colour."""

    __tablename__ = "speaker_stats"

    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    meeting_id: Mapped[str] = mapped_column(
        ForeignKey("meetings.id", ondelete="CASCADE"), nullable=False, index=True
    )
    position: Mapped[int] = mapped_column(Integer, nullable=False)

    name: Mapped[str] = mapped_column(String(255), nullable=False)
    seconds: Mapped[float] = mapped_column(Float, nullable=False, default=0.0)
    time_label: Mapped[str | None] = mapped_column(String(16))
    pct: Mapped[float] = mapped_column(Float, nullable=False, default=0.0)
    color: Mapped[str | None] = mapped_column(String(16))

    meeting: Mapped[Meeting] = relationship(back_populates="speaker_stats")

    __table_args__ = (
        UniqueConstraint("meeting_id", "name", name="uq_speaker_meeting_name"),
        CheckConstraint("pct >= 0 AND pct <= 100", name="ck_speaker_pct"),
    )


class MeetingLanguage(Base):
    """Seconds and share per language across one meeting."""

    __tablename__ = "meeting_languages"

    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    meeting_id: Mapped[str] = mapped_column(
        ForeignKey("meetings.id", ondelete="CASCADE"), nullable=False, index=True
    )
    position: Mapped[int] = mapped_column(Integer, nullable=False)

    code: Mapped[str] = mapped_column(String(8), nullable=False)
    name: Mapped[str] = mapped_column(String(64), nullable=False)
    seconds: Mapped[float] = mapped_column(Float, nullable=False, default=0.0)
    pct: Mapped[float] = mapped_column(Float, nullable=False, default=0.0)

    meeting: Mapped[Meeting] = relationship(back_populates="languages")

    __table_args__ = (
        UniqueConstraint("meeting_id", "code", name="uq_language_meeting_code"),
        CheckConstraint("pct >= 0 AND pct <= 100", name="ck_language_pct"),
    )


# --- Summarization outputs -------------------------------------------------
# Written by models/summarizer.py via db/repository.py:_apply_children once a
# meeting's transcript has been summarized.


class Decision(Base):
    __tablename__ = "decisions"

    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    meeting_id: Mapped[str] = mapped_column(
        ForeignKey("meetings.id", ondelete="CASCADE"), nullable=False, index=True
    )
    position: Mapped[int] = mapped_column(Integer, nullable=False)
    text: Mapped[str] = mapped_column(Text, nullable=False)
    # The exact transcript line this decision was verified against. Nullable
    # only for rows written before this column existed.
    quote: Mapped[str | None] = mapped_column(Text)
    source_time: Mapped[str | None] = mapped_column(String(32))

    meeting: Mapped[Meeting] = relationship(back_populates="decisions")

    __table_args__ = (
        UniqueConstraint("meeting_id", "position", name="uq_decision_meeting_position"),
    )


class ActionItem(Base):
    __tablename__ = "action_items"

    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    meeting_id: Mapped[str] = mapped_column(
        ForeignKey("meetings.id", ondelete="CASCADE"), nullable=False, index=True
    )
    position: Mapped[int] = mapped_column(Integer, nullable=False)

    title: Mapped[str] = mapped_column(Text, nullable=False)
    assignee: Mapped[str | None] = mapped_column(String(255))
    due: Mapped[str | None] = mapped_column(String(64))
    color: Mapped[str | None] = mapped_column(String(16))
    # Same provenance fields as Decision.quote / Decision.source_time above.
    quote: Mapped[str | None] = mapped_column(Text)
    source_time: Mapped[str | None] = mapped_column(String(32))

    meeting: Mapped[Meeting] = relationship(back_populates="action_items")

    __table_args__ = (
        UniqueConstraint("meeting_id", "position", name="uq_action_meeting_position"),
    )


class Keyword(Base):
    __tablename__ = "keywords"

    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    meeting_id: Mapped[str] = mapped_column(
        ForeignKey("meetings.id", ondelete="CASCADE"), nullable=False, index=True
    )
    position: Mapped[int] = mapped_column(Integer, nullable=False)

    word: Mapped[str] = mapped_column(String(255), nullable=False)
    count: Mapped[int] = mapped_column(Integer, nullable=False, default=0)

    meeting: Mapped[Meeting] = relationship(back_populates="keywords")

    __table_args__ = (
        UniqueConstraint("meeting_id", "word", name="uq_keyword_meeting_word"),
        CheckConstraint("count >= 0", name="ck_keyword_count"),
    )


class Speaker(Base):
    """
    An enrolled voice profile.

    Moved out of speakers.json so voiceprints live under the same backup,
    transaction and access story as everything else.

    `centroid` is the running average of every enrollment sample for this
    person, L2-normalised. `sample_count` is how many samples went into it —
    both are needed, because enrolling the same name again blends into the
    existing profile weighted by that count rather than overwriting it.

    Stored as JSON text rather than a float array: pgvector would be the right
    type, but it is an extension this deployment does not have, and
    identification compares against a handful of profiles in Python anyway.

    This is biometric data. It is unencrypted and behind no authentication.
    """

    __tablename__ = "speakers"

    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    name: Mapped[str] = mapped_column(String(255), nullable=False, unique=True, index=True)
    centroid: Mapped[str] = mapped_column(Text, nullable=False)
    sample_count: Mapped[int] = mapped_column(
        Integer, nullable=False, default=1, server_default="1"
    )
    created_at: Mapped[dt.datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )
    updated_at: Mapped[dt.datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now(), onupdate=func.now()
    )

    __table_args__ = (CheckConstraint("sample_count >= 1", name="ck_speakers_sample_count"),)
