"""add meetings.summary_engine

Revision ID: 5458ba8de72a
Revises: 20680bce886a
Create Date: 2026-07-30 10:36:14.263637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5458ba8de72a'
down_revision: Union[str, None] = '20680bce886a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meetings', sa.Column('summary_engine', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meetings', 'summary_engine')
    # ### end Alembic commands ###
