"""initial schema

Revision ID: 8d126cd152a9
Revises: 
Create Date: 2026-07-29 16:46:40.611760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d126cd152a9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meetings',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('agenda', sa.Text(), nullable=True),
    sa.Column('file_name', sa.String(length=512), nullable=False),
    sa.Column('file_type', sa.String(length=255), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('file_size_label', sa.String(length=32), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('failed_segments', sa.Integer(), nullable=False),
    sa.Column('duration', sa.String(length=32), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=False),
    sa.Column('participants', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=64), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('Processing', 'Completed', 'Failed')", name='ck_meetings_status'),
    sa.CheckConstraint('file_size_bytes >= 0', name='ck_meetings_file_size'),
    sa.CheckConstraint('progress >= 0 AND progress <= 100', name='ck_meetings_progress'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meetings_status'), 'meetings', ['status'], unique=False)
    op.create_index(op.f('ix_meetings_uploaded_at'), 'meetings', ['uploaded_at'], unique=False)
    op.create_index('ix_meetings_uploaded_at_desc', 'meetings', [sa.text('uploaded_at DESC')], unique=False)
    op.create_table('speakers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('embedding', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_speakers_name'), 'speakers', ['name'], unique=True)
    op.create_table('action_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.String(length=64), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('assignee', sa.String(length=255), nullable=True),
    sa.Column('due', sa.String(length=64), nullable=True),
    sa.Column('color', sa.String(length=16), nullable=True),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('meeting_id', 'position', name='uq_action_meeting_position')
    )
    op.create_index(op.f('ix_action_items_meeting_id'), 'action_items', ['meeting_id'], unique=False)
    op.create_table('decisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.String(length=64), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('meeting_id', 'position', name='uq_decision_meeting_position')
    )
    op.create_index(op.f('ix_decisions_meeting_id'), 'decisions', ['meeting_id'], unique=False)
    op.create_table('keywords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.String(length=64), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(length=255), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.CheckConstraint('count >= 0', name='ck_keyword_count'),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('meeting_id', 'word', name='uq_keyword_meeting_word')
    )
    op.create_index(op.f('ix_keywords_meeting_id'), 'keywords', ['meeting_id'], unique=False)
    op.create_table('meeting_languages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.String(length=64), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=8), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('seconds', sa.Float(), nullable=False),
    sa.Column('pct', sa.Float(), nullable=False),
    sa.CheckConstraint('pct >= 0 AND pct <= 100', name='ck_language_pct'),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('meeting_id', 'code', name='uq_language_meeting_code')
    )
    op.create_index(op.f('ix_meeting_languages_meeting_id'), 'meeting_languages', ['meeting_id'], unique=False)
    op.create_table('speaker_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.String(length=64), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('seconds', sa.Float(), nullable=False),
    sa.Column('time_label', sa.String(length=16), nullable=True),
    sa.Column('pct', sa.Float(), nullable=False),
    sa.Column('color', sa.String(length=16), nullable=True),
    sa.CheckConstraint('pct >= 0 AND pct <= 100', name='ck_speaker_pct'),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('meeting_id', 'name', name='uq_speaker_meeting_name')
    )
    op.create_index(op.f('ix_speaker_stats_meeting_id'), 'speaker_stats', ['meeting_id'], unique=False)
    op.create_table('transcript_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.String(length=64), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('start_sec', sa.Float(), nullable=False),
    sa.Column('end_sec', sa.Float(), nullable=False),
    sa.Column('time_label', sa.String(length=16), nullable=True),
    sa.Column('speaker', sa.String(length=255), nullable=False),
    sa.Column('speaker_label', sa.String(length=255), nullable=True),
    sa.Column('identified_as', sa.String(length=255), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('color', sa.String(length=16), nullable=True),
    sa.Column('language', sa.String(length=8), nullable=True),
    sa.Column('language_name', sa.String(length=64), nullable=True),
    sa.Column('language_prob', sa.Float(), nullable=False),
    sa.Column('language_detected', sa.String(length=8), nullable=True),
    sa.Column('language_fallback', sa.Boolean(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.CheckConstraint('end_sec >= start_sec', name='ck_transcript_time_order'),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('meeting_id', 'position', name='uq_transcript_meeting_position')
    )
    op.create_index(op.f('ix_transcript_lines_language'), 'transcript_lines', ['language'], unique=False)
    op.create_index(op.f('ix_transcript_lines_meeting_id'), 'transcript_lines', ['meeting_id'], unique=False)
    op.create_index(op.f('ix_transcript_lines_speaker'), 'transcript_lines', ['speaker'], unique=False)
    op.create_index('ix_transcript_meeting_position', 'transcript_lines', ['meeting_id', 'position'], unique=False)
    # ### end Alembic commands ###

    # --- Full-text search (hand-written; autogenerate cannot infer these) ---
    #
    # The 'simple' text search configuration is deliberate. 'english' applies
    # English stemming and an English stopword list, which is meaningless for
    # Hindi and Marathi and would mangle Devanagari tokens. 'simple' does
    # nothing but lowercase and tokenize, so all three languages are treated
    # identically — which is what a trilingual transcript needs.
    #
    # GIN over an expression index: Postgres can only use these if the query
    # spells the expression exactly the same way. repository.search() does.
    op.execute(
        "CREATE INDEX ix_transcript_lines_fts ON transcript_lines "
        "USING GIN (to_tsvector('simple', text))"
    )
    op.execute(
        "CREATE INDEX ix_meetings_fts ON meetings "
        "USING GIN (to_tsvector('simple', coalesce(title, '') || ' ' || coalesce(agenda, '')))"
    )

    # Trigram index for substring/typo-tolerant matching on titles. pg_trgm
    # ships with postgresql-contrib; skipped with a notice if unavailable so a
    # bare Postgres install still migrates cleanly.
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    op.execute(
        "CREATE INDEX ix_meetings_title_trgm ON meetings USING GIN (title gin_trgm_ops)"
    )


def downgrade() -> None:
    op.execute("DROP INDEX IF EXISTS ix_meetings_title_trgm")
    op.execute("DROP INDEX IF EXISTS ix_meetings_fts")
    op.execute("DROP INDEX IF EXISTS ix_transcript_lines_fts")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_transcript_meeting_position', table_name='transcript_lines')
    op.drop_index(op.f('ix_transcript_lines_speaker'), table_name='transcript_lines')
    op.drop_index(op.f('ix_transcript_lines_meeting_id'), table_name='transcript_lines')
    op.drop_index(op.f('ix_transcript_lines_language'), table_name='transcript_lines')
    op.drop_table('transcript_lines')
    op.drop_index(op.f('ix_speaker_stats_meeting_id'), table_name='speaker_stats')
    op.drop_table('speaker_stats')
    op.drop_index(op.f('ix_meeting_languages_meeting_id'), table_name='meeting_languages')
    op.drop_table('meeting_languages')
    op.drop_index(op.f('ix_keywords_meeting_id'), table_name='keywords')
    op.drop_table('keywords')
    op.drop_index(op.f('ix_decisions_meeting_id'), table_name='decisions')
    op.drop_table('decisions')
    op.drop_index(op.f('ix_action_items_meeting_id'), table_name='action_items')
    op.drop_table('action_items')
    op.drop_index(op.f('ix_speakers_name'), table_name='speakers')
    op.drop_table('speakers')
    op.drop_index('ix_meetings_uploaded_at_desc', table_name='meetings')
    op.drop_index(op.f('ix_meetings_uploaded_at'), table_name='meetings')
    op.drop_index(op.f('ix_meetings_status'), table_name='meetings')
    op.drop_table('meetings')
    # ### end Alembic commands ###
